// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYTFvu77GCSZp8ijRG8084mTxBm-Fb5ug',
    appId: '1:553775054490:web:f0fcb7feb6b291bb15e923',
    messagingSenderId: '553775054490',
    projectId: 'hob-sparcs',
    authDomain: 'hob-sparcs.firebaseapp.com',
    storageBucket: 'hob-sparcs.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5BcXe8J1O5AAMq5YzwiGIXHn4MMKAoVw',
    appId: '1:553775054490:android:5c8b8d8df534db1b15e923',
    messagingSenderId: '553775054490',
    projectId: 'hob-sparcs',
    storageBucket: 'hob-sparcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDODy6BbebeaFvodQ799_ywnqGjWwb94OY',
    appId: '1:553775054490:ios:09a653b93557ec3c15e923',
    messagingSenderId: '553775054490',
    projectId: 'hob-sparcs',
    storageBucket: 'hob-sparcs.appspot.com',
    iosClientId:
        '553775054490-a2td2ouficq83pbicf8ifh09fe71ufvg.apps.googleusercontent.com',
    iosBundleId: 'com.example.application',
  );
}
